export const DASHBOARD = '/'
export const SEARCH = '/search/:keyword'
export const EXPLORE = '/explore'
export const SUBSCRIPTION = '/subscription/'
export const CHANNEL = '/channel/:channel'
export const WATCH = '/watch/:video'
